version: '3'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: med_app_backend
    container_name: med_app_backend
    command: npm start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9000:9000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: med_app_frontend
    container_name: med_app_frontend
    command: npm start 
    volumes:
      - ./client/src:/usr/app/src
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"

volumes:
  node_modules:
  web-root:
    driver: local